; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp___std_terminate:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp___CxxFrameHandler3:PROC
PUBLIC	?__autoclassinit2@MainGame@@QEAAX_K@Z		; MainGame::__autoclassinit2
PUBLIC	SDL_main
EXTRN	__CxxFrameHandler3:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__GSHandlerCheck_EH:PROC
EXTRN	__std_terminate:PROC
EXTRN	__security_cookie:QWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$SDL_main DD imagerel $LN11
	DD	imagerel $LN11+94
	DD	imagerel $unwind$SDL_main
;	COMDAT xdata
xdata	SEGMENT
$unwind$SDL_main DD 011319H
	DD	08204H
	DD	imagerel __GSHandlerCheck
	DD	038H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT SDL_main
_TEXT	SEGMENT
game$ = 32
__$ArrayPad$ = 56
argc$ = 80
argv$ = 88
SDL_main PROC						; COMDAT
; File c:\agil\works\programming\gamedev\sdl2\project\subur\subur\subur\main.cpp
; Line 4
$LN11:
	sub	rsp, 72					; 00000048H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
	xor	eax, eax
; Line 6
	lea	rcx, QWORD PTR game$[rsp]
	mov	QWORD PTR game$[rsp], rax
	mov	QWORD PTR game$[rsp+8], rax
	mov	QWORD PTR game$[rsp+16], rax
	call	?run@MainGame@@QEAAXXZ			; MainGame::run
; File c:\agil\works\programming\gamedev\sdl2\project\subur\subur\subur\main_game.cpp
; Line 13
	mov	rcx, QWORD PTR game$[rsp+8]
	call	QWORD PTR __imp_SDL_DestroyRenderer
; Line 14
	mov	rcx, QWORD PTR game$[rsp]
	call	QWORD PTR __imp_SDL_DestroyWindow
; Line 15
	call	QWORD PTR __imp_SDL_Quit
; File c:\agil\works\programming\gamedev\sdl2\project\subur\subur\subur\main.cpp
; Line 8
	xor	eax, eax
; Line 9
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 72					; 00000048H
	ret	0
SDL_main ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?__autoclassinit2@MainGame@@QEAAX_K@Z
_TEXT	SEGMENT
this$ = 8
classSize$dead$ = 16
?__autoclassinit2@MainGame@@QEAAX_K@Z PROC		; MainGame::__autoclassinit2, COMDAT
	xor	eax, eax
	mov	QWORD PTR [rcx], rax
	mov	QWORD PTR [rcx+8], rax
	mov	QWORD PTR [rcx+16], rax
	ret	0
?__autoclassinit2@MainGame@@QEAAX_K@Z ENDP		; MainGame::__autoclassinit2
_TEXT	ENDS
END
